name: Test snap builds

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "snap/**"
      - ".github/workflows/test-snap-builds.yml"
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build snap
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Show log on failure
        if: failure()
        run: |
          cat /home/runner/.local/state/snapcraft/log/snapcraft*.log 2>/dev/null || true
          exit 1

      - name: Review snap
        uses: diddlesnaps/snapcraft-review-action@v1
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          isClassic: "false"

      - name: Upload snap
        uses: actions/upload-artifact@v4
        with:
          name: snap-amd64
          path: ${{ steps.snapcraft.outputs.snap }}
          retention-days: 7
